var mascots = ["mascot1.png",
	       "mascot2.png",
	       "mascot3.png",
	       "mascot4.gif",
	       "mascot5.png",
	       "mascot6.png",
	       "mascot7.png",
	       "mascot8.png",
	       "mascot9.png",
	       "mascot10.png",
	       "mascot11.png",
	       "mascot12.png",
	       "mascot13.png",
	       "mascot14.png",
	       "mascot15.png"];
